# Generated by Django 4.2 on 2024-04-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode_info',
            name='reports',
            field=models.FileField(blank=True, upload_to='reports'),
        ),
    ]
