# Generated by Django 4.2.11 on 2024-04-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qrcode", "0002_a"),
    ]

    operations = [
        migrations.DeleteModel(
            name="A",
        ),
        migrations.RemoveField(
            model_name="qrcode_info",
            name="encryption_key",
        ),
    ]
