# Generated by Django 4.2.11 on 2024-04-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='encryption_key',
            field=models.CharField(default='', max_length=30),
        ),
    ]
